### ISSUE TITLE
Add Stalebot to Enhancements repo

### ISSUE THREAD

**Issue by dfarrell07** [submariner-io/enhancements#228] opened 2024-06-25 13:48 UTC
We didn't add it initially because of the timescale of these issues, but now we have lots of very old ones we should likely keep in the rest of the triage/scrub system.

**Comment by maayanf24** [comment] 2024-11-03 09:14
Duplicate of https://github.com/submariner-io/enhancements/issues/147

**Closed as completed by maayanf24** 2024-11-03 09:14 UTC
Labels: automation
